loda:
  email: ngtrphuong@gmail.com
  googleAnalyticsId: U-AbcDeF123456789GHREWDhewdHRFDFHJWwewddfd
  authors:
    - ngtrphuong
    - Moon
    - Moc
    - Be Han
  exampleMap:
    key1: hello Be Han
    key2: My Sweetie